# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GRpqy5o_7wJDBNStsRS_3ZngBoxzaSyE
"""

!pip install rdkit
import pandas as pd
from rdkit import Chem
from rdkit.Chem import Draw
import matplotlib.pyplot as plt

file = 'tested_molecules.csv'
molecule_data = pd.read_csv(file)

smiles_list = molecule_data['SMILES'].tolist()

molecules = [Chem.MolFromSmiles(smiles) for smiles in smiles_list[:5]]

plt.figure(figsize=(100, 100))
for i, mol in enumerate(molecules):
    plt.subplot(1, len(molecules), i + 1)
    img = Draw.MolToImage(mol)
    plt.imshow(img)
    plt.axis('off')

plt.show()
